name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Plan and validate
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        working-directory: ./infrastructure/test-env

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v3

      - name:  Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  

      - name:  Terraform Init
        run: terraform init

      - name:  Terraform Validate
        run: terraform validate

      - name:  Terraform Plan
        run: terraform plan -out=tfplan
